services:
  mysql:
    image: whatsm97/database:latest
    platform: linux/amd64
    container_name: database
    environment:
      MYSQL_ROOT_PASSWORD: mypassword
    ports:
      - "3306:3306"
    networks:
      - my_networkSQL
    volumes:
      - mysql_data:/var/lib/mysql
      - ./db:/docker-entrypoint-initdb.d ## it is used to initialize the database, only if the volume is empty
    restart: always
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 3

  db-init: ## should have installed mysql client on the php-apache image, i have to use the mysql image
    image: mysql:latest
    platform: linux/amd64
    container_name: db-init
    command: >
      /bin/bash -c "
        echo 'Waiting for MySQL to start...'
        while ! mysql -h database -u root -pmypassword -e 'SELECT 1' >/dev/null 2>&1; do
          sleep 1
        done
        echo 'MySQL started, executing initialization script...'
        mysql -h database -u root -pmypassword < /sql_scripts/ChapterOne.sql
       

        echo 'Initialization completed'
      "
    networks:
      - my_networkSQL
    volumes:
      - ./db:/sql_scripts
    depends_on:
      mysql:
        condition: service_started

  
  php-apache:
    image: whatsm97/sito:latest
    platform: linux/amd64
    container_name: sito
    command: >
      /bin/bash -c "
        echo 'DB Population in progress...'
        php /var/www/populateDB.php
        echo 'Database population completed, starting Apache...'
        apache2-foreground
      "
    ports:
      - "8080:80"
    volumes:
      - ./src:/var/www/html
      - ./db:/var/www
    networks:
      - my_networkSQL
    depends_on:
      db-init:
        condition: service_completed_successfully
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80"]
      interval: 10s
      timeout: 5s
      retries: 3

networks:
  my_networkSQL:
    driver: bridge
volumes:
  mysql_data: