DROP DATABASE IF EXISTS Chapter_one;
CREATE DATABASE Chapter_one;

USE Chapter_one;

CREATE TABLE CUSTOMER (
    Id INT AUTO_INCREMENT PRIMARY KEY,
    First_name VARCHAR(100) NOT NULL,
    Last_name VARCHAR(100) NOT NULL,
    Email VARCHAR(100) UNIQUE NOT NULL,
    Password VARCHAR(255) NOT NULL,
    Address VARCHAR(255) NOT NULL,
    Phone VARCHAR(20) NOT NULL
);

CREATE TABLE ADMIN (
    Id INT AUTO_INCREMENT PRIMARY KEY,
    First_name VARCHAR(100) NOT NULL,
    Last_name VARCHAR(100) NOT NULL,
    Email VARCHAR(100) UNIQUE NOT NULL,
    Password VARCHAR(255) NOT NULL
);

CREATE TABLE AUTHOR (
    Id INT AUTO_INCREMENT PRIMARY KEY,
    First_name VARCHAR(100) NOT NULL,
    Last_name VARCHAR(100) NOT NULL,
    UNIQUE (First_name, Last_name)
);

CREATE TABLE CATEGORY (
    Id INT AUTO_INCREMENT PRIMARY KEY,
    Name VARCHAR(100) UNIQUE NOT NULL
);

CREATE TABLE PUBLISHER (
    Id INT AUTO_INCREMENT PRIMARY KEY,
    Name VARCHAR(100) UNIQUE NOT NULL
);

CREATE TABLE BOOK (
    Id INT AUTO_INCREMENT PRIMARY KEY,
    Title VARCHAR(255) NOT NULL,
    Description TEXT,
    Price DECIMAL(10, 2) NOT NULL,
    Cover VARCHAR(255) NOT NULL,
    Category_id INT ,
    Publisher_id INT ,
    Author_id INT ,
    FOREIGN KEY (Category_id) REFERENCES CATEGORY(Id) ON DELETE SET NULL,
    FOREIGN KEY (Author_id) REFERENCES AUTHOR(Id) ON DELETE SET NULL,
    FOREIGN KEY (Publisher_id) REFERENCES PUBLISHER(Id) ON DELETE SET NULL
);

CREATE TABLE POST (
    Id INT AUTO_INCREMENT PRIMARY KEY,
    Text TEXT NOT NULL,
    Publication_date DATETIME NOT NULL,
    Author_id INT,
    Book_id INT,
    FOREIGN KEY (Author_id) REFERENCES AUTHOR(Id) ON DELETE CASCADE,
    FOREIGN KEY (Book_id) REFERENCES BOOK(Id) ON DELETE CASCADE
);

CREATE TABLE REVIEW (
    Id INT AUTO_INCREMENT PRIMARY KEY,
    Text TEXT,
    Rating INT CHECK (Rating BETWEEN 1 AND 5),
    Book_id INT NOT NULL,
    Customer_id INT NOT NULL,
    FOREIGN KEY (Book_id) REFERENCES BOOK(Id),
    FOREIGN KEY (Customer_id) REFERENCES CUSTOMER(Id) ON DELETE CASCADE,
    UNIQUE (Book_id, Customer_id)
);

CREATE TABLE CART (
    Id INT AUTO_INCREMENT PRIMARY KEY,
    Subtotal DECIMAL(10, 2) DEFAULT 0,
    Last_modified DATETIME DEFAULT CURRENT_TIMESTAMP,
    Item_count INT DEFAULT 0,
    Customer_id INT NOT NULL,
    FOREIGN KEY (Customer_id) REFERENCES CUSTOMER(Id) ON DELETE CASCADE
);

CREATE TABLE BOOK_IN_CART (
    Id INT AUTO_INCREMENT PRIMARY KEY,
    Cart_id INT NOT NULL,
    Book_id INT NOT NULL,
    Quantity INT DEFAULT 1,
    FOREIGN KEY (Cart_id) REFERENCES CART(Id) ON DELETE CASCADE,
    FOREIGN KEY (Book_id) REFERENCES BOOK(Id) ON DELETE CASCADE
);

CREATE TABLE DISCOUNT_CODE (
    Id INT AUTO_INCREMENT PRIMARY KEY,
    Code VARCHAR(50) UNIQUE NOT NULL,
    Type ENUM('percentage', 'fixed') NOT NULL,
    Value DECIMAL(10, 2) NOT NULL,
    Start_date DATE NOT NULL,
    End_date DATE NOT NULL,
    Single_use BOOLEAN DEFAULT FALSE,
    Active BOOLEAN DEFAULT TRUE
);

CREATE TABLE `ORDER` (
    Id INT AUTO_INCREMENT PRIMARY KEY,
    Date DATETIME DEFAULT CURRENT_TIMESTAMP,
    Total DECIMAL(10, 2) NOT NULL,
    Customer_id INT NOT NULL,
    Discount_code_id INT NULL,
    Status ENUM('pending', 'sent', 'failed') DEFAULT 'pending',
    FOREIGN KEY (Customer_id) REFERENCES CUSTOMER(Id) ON DELETE CASCADE,
    FOREIGN KEY (Discount_code_id) REFERENCES DISCOUNT_CODE(Id)
);

CREATE TABLE ORDER_DETAIL (
    Id INT AUTO_INCREMENT PRIMARY KEY,
    Quantity INT NOT NULL,
    Subtotal DECIMAL(10, 2) NOT NULL,
    Order_id INT NOT NULL,
    Book_id INT NOT NULL,
    FOREIGN KEY (Order_id) REFERENCES `ORDER`(Id) ON DELETE CASCADE,
    FOREIGN KEY (Book_id) REFERENCES BOOK(Id)
);

CREATE TABLE DISCOUNT_CODE_USAGE (
    Id INT AUTO_INCREMENT PRIMARY KEY,
    Usage_date DATETIME DEFAULT CURRENT_TIMESTAMP,
    Discount_code_id INT,
    Customer_id INT,
    Order_id INT,
    FOREIGN KEY (Discount_code_id) REFERENCES DISCOUNT_CODE(Id),
    FOREIGN KEY (Customer_id) REFERENCES CUSTOMER(Id) ON DELETE CASCADE,
    FOREIGN KEY (Order_id) REFERENCES `ORDER`(Id) ON DELETE CASCADE
);

CREATE TABLE ORDER_NOTIFICATION (
    Id INT AUTO_INCREMENT PRIMARY KEY,
    Order_id INT NOT NULL,
    Message TEXT NOT NULL,
    Status ENUM('pending', 'sent', 'failed') DEFAULT 'pending',
    FOREIGN KEY (Order_id) REFERENCES `ORDER`(Id) ON DELETE CASCADE
);

-- TRIGGER -- 

CREATE TRIGGER after_insert_book_in_cart
AFTER INSERT ON BOOK_IN_CART
FOR EACH ROW
BEGIN
    UPDATE CART 
    SET Item_count = Item_count + NEW.Quantity, 
        Subtotal = Subtotal + (NEW.Quantity * (SELECT Price FROM BOOK WHERE Id = NEW.Book_id)),
        Last_modified = CURRENT_TIMESTAMP
    WHERE Id = NEW.Cart_id;
END;

CREATE TRIGGER after_delete_book_in_cart
AFTER DELETE ON BOOK_IN_CART
FOR EACH ROW
BEGIN
    UPDATE CART 
    SET Item_count = Item_count - OLD.Quantity, 
        Subtotal = Subtotal - (OLD.Quantity * (SELECT Price FROM BOOK WHERE Id = OLD.Book_id)),
        Last_modified = CURRENT_TIMESTAMP
    WHERE Id = OLD.Cart_id;
END;


-- Trigger per creare un carrello quando viene creato un nuovo cliente
CREATE TRIGGER after_insert_customer
AFTER INSERT ON CUSTOMER
FOR EACH ROW
BEGIN
    INSERT INTO CART (Customer_id) VALUES (NEW.Id);
END;

